name: ShareWorthy
favicon: null
layout_spectrum: 0.8192603029310703
typography_spectrum: 0.41637541726231575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-311190-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4973a3'
    - '#bbc8d1'
    - '#020307'
    - '#bc7d00'
    - '#ffb500'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
