name: ShareWorthy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41637541726231575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-311190-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010100'
    - '#656893'
    - '#543650'
    - '#fefe57'
    - '#fe7c5c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
