name: ShareWorthy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41637541726231575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-311190-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f4f0'
    - '#fc6f51'
    - '#000000'
    - '#8a8a8a'
    - '#444444'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
